kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-nd-capstone-project
  labels:
    app: devops-nd-capstone-project
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: devops-nd-capstone-project
  template:
    metadata:
      labels:
        app: devops-nd-capstone-project
    spec:
      containers:
        - name: devops-nd-capstone-project
          imagePullPolicy: Always
          image: babawale/devops-nd-capstone-project:latest
          ports:
            - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: devops-nd-capstone-project
  labels:
    app: devops-nd-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: devops-nd-capstone-project
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP