apiVersion: v1
kind: Service
metadata:
  name: devops-nd-capstone-project
  labels:
    app: devops-nd-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: devops-nd-capstone-project
  ports:
    - port: 80
      targetPort: 80
